### ISSUE TITLE
Edit the hazelcast.xml file

### ISSUE THREAD

**Issue by Asaibaba** [hazelcast-guides/kubernetes#20]
Hello, 
I have deployed operator based Hazelcast service  using below commands

```

helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com/
helm repo update
helm install operator hazelcast/hazelcast-platform-operator --set installCRDs=true
cat << EOF | kubectl apply -f -
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hz-hazelcast
EOF 

```
I am unable to edit the /opt/hazelcast/config/hazelcast.xml file, it had read only permission.
Using configmap passed hazelcast.xml using below cr.yaml, it is present in the pod but not working as expected.

```
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast-test
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast'
  version: '5.3.1-slim'
  userCodeDeployment:
     configMaps:
       - hazelcast-config-configmap
```
Need to change the cluster name and container port some other configuration in hazelcast.xml file.
Please provide me some solution on this.
